### ISSUE TITLE
Unable to load from json data archive file inside svf package

### ISSUE THREAD

**Issue by designlab87** [dukedhx/viewer-ioniccapacitor-angular#1]
I have loaded my own files into forge, extracted them, and downloaded the svf packages. When I run this project with your example svf, the viewer loads up fine, but when I point to my svf, I get the following errors:

E/Capacitor: Unable to open asset URL: http://localhost/assets/models/weston/Materials.json.gz
E/Capacitor/Console: File: https://developer.api.autodesk.com/modelderivative/v2/viewers/viewer3D.min.js?v=v7.* - Line 19 - Msg: Error while processing SVF: {"url":"http://localhost/assets/models/weston/Materials.json.gz","httpStatus":404,"httpStatusText":"OK"}

The Materials.json.gz file is there, and there is json data in it. I also checked permissions on the files and folders. It appears the javascript in the model derivative api cannot access the json. Am I interpreting the error incorrectly? I would welcome any help you could offer. Thanks

**Comment by dukedhx** [comment]
are you sure the file is bundled in the correct path? can you access the file in your app (like via a link to the file path?

If the issue persists upload your SVFs to GDrive/dropbox etc and drop the link so I can take a look

**Comment by designlab87** [comment]
Yes, the .gz file is in the same directory as the .svf.  And I was following the same setup as in your sample. The only thing I changed was line 9 of src/app/viewer/forge.viewer.ts.  I added the path to my .svf, which is:

svfURL = 'assets/models/weston/weston.svf';

Here is a link to the .svf package:

https://drive.google.com/open?id=1FHxkN15Ra0OOCMttgNKS1NdbIAKleUyK

**Comment by designlab87** [comment]
When I run npm start it loads properly in the browser, it just runs into the error when loading into Android studio and running on emulator. The javascript from autodesk.com seems to load in the other resources in the SVF package, but stops on this file.

**Comment by dukedhx** [comment]
Sorry to get back late - was away on extra break due to the coronavirus outbreak.

However I was unable to reproduce the issue - your model loads fine when I tried:
![image](https://user-images.githubusercontent.com/10786558/74135540-6c24ad80-4c27-11ea-8b0c-9640fd11fbe4.png)

Here's my setup:

```
// src/forge.viewer.ts
export class ForgeViewer {
  svfURL = 'assets/models/weston/weston.svf';
```
```
.
├── app
│   ├── app-routing.module.ts
│   ├── app.component.html
│   ├── app.component.scss
│   ├── app.component.spec.ts
│   ├── app.component.ts
│   ├── app.module.ts
│   ├── shared
│   │   └── services
│   │       └── forgeViewerLoader.service.ts
│   └── viewer
│       ├── forge.viewer.html
│       ├── forge.viewer.module.ts
│       ├── forge.viewer.scss
│       ├── forge.viewer.spec.ts
│       └── forge.viewer.ts
├── assets
│   ├── icon
│   │   └── favicon.png
│   ├── models
│   │   └── weston
│   │       ├── 0.pf
│   │       ├── 0_0_0.9152F9BC539BCC31208EBEF9B803EDC2.jpg
│   │       ├── Antenor_groundTop.png
│   │       ├── Antenor_middle.png
│   │       ├── Apemantus_groundTop.png
│   │       ├── Apemantus_middle.png
│   │       ├── CameraDefinitions.bin
│   │       ├── CameraList.bin
│   │       ├── Curb.jpg
│   │       ├── Elisabeth_groundTop.png
│   │       ├── Elisabeth_middle.png
│   │       ├── FragmentList.pack
│   │       ├── GeometryMetadata.pf
│   │       ├── InstanceTree.bin
│   │       ├── Lear_groundTop.png
│   │       ├── Lear_middle.png
│   │       ├── LightDefinitions.bin
│   │       ├── LightList.bin
│   │       ├── Materials.json.gz
│   │       ├── Paulus_groundTop.png
│   │       ├── Set.bin
│   │       ├── asphalt2.jpg
│   │       ├── bench01.jpg
│   │       ├── bikebricks01.jpg
│   │       ├── concrete.jpg
│   │       ├── diamond03.jpg
│   │       ├── kiesdecke_2.jpg
│   │       ├── objects_attrs.json.gz
│   │       ├── objects_avs.json.gz
│   │       ├── objects_ids.json.gz
│   │       ├── objects_offs.json.gz
│   │       ├── objects_vals.json.gz
│   │       ├── objects_viewables.json.gz
│   │       ├── p_cityBlock04a.jpg
│   │       ├── p_fill01.jpg
│   │       ├── p_fill04a.jpg
│   │       ├── properties.db
│   │       ├── squarebricks.jpg
│   │       ├── stone.jpg
│   │       ├── weston.svf
│   │       ├── weston.svf.png01_thumb_100x100.png
│   │       ├── weston.svf.png01_thumb_200x200.png
│   │       └── weston.svf.png01_thumb_400x400.png
│   └── shapes.svg
├── environments
│   ├── environment.prod.ts
│   └── environment.ts
├── global.scss
├── index.html
├── main.ts
├── polyfills.ts
├── test.ts
├── theme
│   └── variables.scss
└── zone-flags.ts
```

**Comment by designlab87** [comment]
I know this issue is closed, and that the problem must be on my machine, but I am still getting this issue with all SVF's I test with (3 so far). I have tried redownloading the project and reinstalling Android Studio. It can definitely read the file location because in the Android Studio Debug log I get:

D/Capacitor: Handling local request: http://localhost/assets/models/caliper/0.svf
D/Capacitor: Handling local request: http://localhost/assets/models/caliper/0.pf

These appear to be seen and handled fine, but then it is unable to load this file:

E/Capacitor: Unable to open asset URL: http://localhost/assets/models/caliper/Materials.json.gz

Which is right in the same location. Then the debugger throws the error:

E/Capacitor/Console: File: https://developer.api.autodesk.com/modelderivative/v2/viewers/viewer3D.min.js?v=v7.* - Line 19 - Msg: Error while processing SVF: {"url":"http://localhost/assets/models/caliper/Materials.json.gz","httpStatus":404,"httpStatusText":"OK"}

I am using Windows 10, Android Studio 3.6, Android SDK 28, java 8, Gradle 4.1, node 12.15, npx 6.13.7, angular 8.1.3, and I am launching 'app' on Pixel 2 API 28

I have tried checking file permissions, pausing anti-virus software, regenerating the SVF's, 

I welcome any help you could offer. Thanks
